### ISSUE TITLE
significant performance drop for some examples

### ISSUE THREAD

**Issue by jakobkroeker** [adipopescu/To-Do-List#28]
the following example drops performance significantly with your patches in comparison to
recent singular spielwiese

```
// finishes in singular-spielwiese in a bit (correct or not?), but
// does not finish in reasonable time using SignatureSB
ring rng = integer,(x,y,z),dp;
option(redSB); option(redTail);
ideal J = -12xy-59xz+40x-22y2,
-109x-22y2z2-42,
69x2z-97x-115y-19;
ideal stdJ  = std(J);
```

in M2: (finishes in a bit)

```
# default is dp ordering:
rng = ZZ[x,y,z]
I = ideal(-12*x*y-59*x*z+40*x-22*y^ 2,-109*x-22*y^ 2*z^ 2-42,69*x^2*z-97*x-115*y-19)
groebnerBasis I
```

**Comment by adipopescu** [comment]
this is because of chain criterion. Over the integers, when activated it gives wrong results.

**Comment by adipopescu** [comment]
The same in this case. Compared M2 output with the singular. In this case M2 has 20 elements, Singular 21. 

reduce(M2,Singular) = 0
reduce(Singular,M2) != 0
reduce(input, Singular) = 0
reduce(input, M2) = 0

lead(m);
_[1]=12xy
_[2]=13590361785xz2
_[3]=2y2z
_[4]=69x2z
_[5]=391287546x3
_[6]=27646102z4
_[7]=649yz3
_[8]=649xz3
_[9]=y2z2
_[10]=xyz2
_[11]=23x2z2
_[12]=3x2yz
_[13]=1688429402y4
_[14]=2xy3
_[15]=6x2y2
_[16]=6x3y
_[17]=518949x4
_[18]=x2z3
_[19]=x2y2z
_[20]=3x4y

_[1]=12xy
_[2]=13590361785xz2
_[3]=2y2z
_[4]=69x2z
_[5]=391287546x3
_[6]=27646102z4
_[7]=649yz3
_[8]=649xz3
_[9]=y2z2
_[10]=xyz2
_[11]=23x2z2
_[12]=3x2yz
_[13]=1688429402y4
_[14]=2xy3
_[15]=6x2y2
_[16]=6x3y
_[17]=518949x4
_[18]=x2z3
_[19]=x2y2z
_[20]=3x4y
_[21]=x4y3
