### ISSUE TITLE
sba(): tail not reduced

### ISSUE THREAD

**Issue by jakobkroeker** [adipopescu/To-Do-List#35]
example:

```
ring rng = (integer),(x,y,z),dp;
option(redSB);
option(redTail);
ideal I = 24*z^2+33*y,-20*y-42,-29*y-39*z;
       ideal gI =  std(I);
       ideal ggI =  std(gI);
       ideal sI =  sba(I);
       ideal ssI =  sba(sI);
sI;
ssI;
```

output:

```
> sI;
sI[1]=y+351z-546
sI[2]=3z-44142
sI[3]=182154
> ssI;
ssI[1]=182154
ssI[2]=3z-44142
ssI[3]=y+63756

```

(351 = 3*117)

**Comment by adipopescu** [comment]
Bei sba tail reduction machen!

**Comment by jakobkroeker** [comment]
fixed? (and test present?)

**Comment by adipopescu** [comment]
Sba over Z is not in Singular!  I am working on it from zero to avoid taking the old bugs with me. 

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: jakobkroeker notifications@github.com 
Datum: 25.10.2015  22:25  (GMT+01:00) 
An: adipopescu/To-Do-List To-Do-List@noreply.github.com 
Cc: Adi Popescu adi_popescum@yahoo.de 
Betreff: Re: [To-Do-List] sba(): tail not reduced (#35) 

fixed? (and test present?)
