### ISSUE TITLE
very bad bug for intersect on SignatureSB branch

### ISSUE THREAD

**Issue by jakobkroeker** [adipopescu/To-Do-List#57]
```
ring rng = integer,(x),dp;
ideal I = -3*x^2-8;
ideal J = 9,5*x^2+8;
option(prot);
ideal I_J =  intersect(I,J); // bad bad
quit;
```

**Comment by adipopescu** [comment]
Tipically if we have to ideals there are two methods:
1 adding a new variable and eliminate it. 
2. building the nice module and compute a syz

By default, the first strategy is used and in this case this is bad.

We can use the other strategy by setting option(interedSyz); and in this case the result is immediate.
Added to tests
